import { useMemo, useState } from 'react';
import { FolderOpen, Grid2X2, List, Search, SlidersHorizontal } from 'lucide-react';
import { Link } from 'wouter';
import { useListProjects } from '@workspace/api-client-react';
import { Badge, Button, EmptyState, ErrorBlock, formatDate, formatTime, LoadingBlock, Panel, StatusDot } from '@/components/ui-kit';

export default function ProjectsPage() {
  const query = useListProjects();
  const projects = query.data ?? [];
  const [search, setSearch] = useState('');
  const [view, setView] = useState<'grid' | 'list'>('grid');
  const filtered = useMemo(() => projects.filter((project) => `${project.name} ${project.fileName}`.toLowerCase().includes(search.toLowerCase())), [projects, search]);
  return (
    <div className="mx-auto max-w-[1400px]">
      <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="max-w-md text-sm leading-6 text-muted-foreground">Your source recordings, organized by what they can become.</p></div><Link href="/upload" className="inline-flex h-10 items-center justify-center rounded-[4px] bg-primary px-4 text-sm font-semibold text-primary-foreground hover:opacity-90" data-testid="link-upload-project">Upload project</Link></div>
      <div className="mb-5 flex flex-wrap items-center gap-3"><div className="relative min-w-[240px] flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="h-10 w-full rounded-[4px] border border-border bg-card pl-9 pr-3 text-sm outline-none focus:border-destructive" placeholder="Search projects…" data-testid="input-search-projects" /></div><Button variant="outline" size="md" className="font-normal" onClick={() => setSearch('')} testId="button-filter-projects"><SlidersHorizontal className="size-3.5" /> Clear filter</Button><div className="flex rounded-[4px] border border-border bg-card p-1"><button className={`rounded p-1.5 ${view === 'grid' ? 'bg-secondary' : 'text-muted-foreground'}`} onClick={() => setView('grid')} data-testid="button-view-grid"><Grid2X2 className="size-3.5" /></button><button className={`rounded p-1.5 ${view === 'list' ? 'bg-secondary' : 'text-muted-foreground'}`} onClick={() => setView('list')} data-testid="button-view-list"><List className="size-3.5" /></button></div></div>
      {query.isLoading ? <LoadingBlock lines={5} /> : query.isError ? <ErrorBlock onRetry={() => query.refetch()} /> : !filtered.length ? <EmptyState icon={FolderOpen} title={search ? 'No matching projects' : 'Your library is waiting'} detail={search ? 'Try a different search term.' : 'Upload your first recording to start finding the moments people replay.'} action={<Link href="/upload" className="inline-flex h-10 items-center rounded-[4px] bg-primary px-4 text-sm font-semibold text-primary-foreground" data-testid="link-empty-upload">Upload a video</Link>} /> : view === 'grid' ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((project) => <ProjectCard key={project.id} project={project} />)}</div> : <Panel className="divide-y divide-border overflow-hidden">{filtered.map((project) => <Link href={`/transcripts?project=${project.id}`} key={project.id} className="flex items-center gap-4 p-4 hover:bg-muted/50" data-testid={`row-project-${project.id}`}><div className="flex size-12 shrink-0 items-center justify-center rounded bg-primary text-primary-foreground"><FolderOpen className="size-4" /></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{project.name}</div><div className="truncate text-xs text-muted-foreground">{project.fileName}</div></div><Badge tone={project.status === 'complete' ? 'lime' : 'neutral'}><span className="flex items-center gap-1.5"><StatusDot status={project.status} /> {project.status}</span></Badge><span className="hidden font-label text-[10px] text-muted-foreground sm:block">{formatTime(project.durationSeconds)}</span><span className="hidden text-xs text-muted-foreground md:block">{formatDate(project.updatedAt)}</span></Link>)}</Panel>}
    </div>
  );
}

function ProjectCard({ project }: { project: { id: string; name: string; fileName: string; durationSeconds: number; status: string; updatedAt: string; thumbnail: string | null } }) {
  return <Link href={`/transcripts?project=${project.id}`} className="group overflow-hidden rounded-[6px] border border-border bg-card hover:-translate-y-0.5 hover:border-primary/35 hover:shadow-lg" data-testid={`card-project-${project.id}`}><div className="relative aspect-[16/8] overflow-hidden bg-[#22333c]" style={project.thumbnail ? { backgroundImage: `url(${project.thumbnail})`, backgroundSize: 'cover', backgroundPosition: 'center' } : undefined}><div className="absolute inset-0 bg-[linear-gradient(135deg,rgba(232,237,81,.24),transparent_48%,rgba(201,77,56,.35))]" /><div className="absolute bottom-3 left-3 font-label text-[9px] tracking-[.14em] text-white/70">SOURCE / {formatTime(project.durationSeconds)}</div><span className="absolute right-3 top-3 rounded-full bg-primary/80 px-2 py-1 font-label text-[9px] uppercase tracking-[.08em] text-primary-foreground">{project.status}</span></div><div className="p-4"><div className="truncate text-sm font-semibold">{project.name}</div><div className="mt-1 truncate text-xs text-muted-foreground">{project.fileName}</div><div className="mt-4 flex items-center justify-between border-t border-border pt-3"><span className="flex items-center gap-2 text-xs text-muted-foreground"><StatusDot status={project.status} /> {project.status}</span><span className="font-label text-[9px] text-muted-foreground">{formatDate(project.updatedAt)}</span></div></div></Link>;
}